### ISSUE TITLE
Override "eval()" function.

### ISSUE THREAD

**Issue by esehara** [puffnfresh/roy#37]
Source :

```
roy> eval("var i = 0")
roy> i
0 : Native
roy> eval("let hoge = 0")
SyntaxError: Unexpected identifier
```

I think eval function should be the function to interpret "String" in its own language.It should be able to interpret JavaScript and Roy,or only Roy.

**Comment by puffnfresh** [comment]
While I'd prefer nobody to use the JS `eval` in Roy, I don't want to modify the execution environment to hide things.

I can't really provide a nice and easy "Roy eval" because that would have a dependency on the whole Roy compiler.

Anyway, it sucks that people can do this:

```
roy> let a = "Test"
roy> eval "a = 100"
100 : Native
roy> a
100 : String
```

But I think that's just the price of using `eval`.
